spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  eskiz:
    simulate: false
    email: abduganiyev.ismoil001@gmail.com
    password: ismoil_0709
    sender-name: 4546
server:
  port: 8443
telegram:
  url: https://hipartsbot.uz/api/v1/telegram
  token: 6412338008:AAFcXM2MXc2mCSUb3Rv3U1fP_JRY9GA77_A
secret:
  click:
    key: iCUfO2CfZkSg
    merchant_user_id : 44167
    service_id : 36335