spring:
  application:
    name: hipartsuz
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hipartsuz
    username: postgres
    password: ismoil_0709
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
bot:
  data:
    ngrok_url : chief-initially-gnat.ngrok-free.app
server:
  port: 8080