spring:
  application:
    name: hipartsuz
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hipartsuz
    username: postgres
    password: <postgres_password>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
bot:
  data:
    ngrok_url : <ngrok_domain>
server:
  port: 8080