package uz.hiparts.hipartsuz.model.enums;

public enum LangFields {
    START,
    BUTTON_CONTACT,
    CHOOSE_LANGUAGE,
    BUTTON_RUSSIAN_LANGUAGE,
    BUTTON_UZBEK_LANGUAGE,
    BUTTON_ENGLISH_LANGUAGE,
    PHONE_NUMBER,
    BUTTON_PHONE_NUMBER,
    USER_PHONE_NUMBER,
    DELIVERY_OR_PICKUP,
    BUTTON_DELIVERY,
    BUTTON_PICKUP,
    BUTTON_SETTINGS,
    BUTTON_NEW_ORDER,
    LANGUAGE_CHANGED,
    BUTTON_CHANGE_LANGUAGE,
    LOCATION,
    BUTTON_LOCATION,
    CONFIRM_ADDRESS,
    BUTTON_YES,
    BUTTON_NO,
    USER_ADDRESS,
    BUTTON_CATALOG
}
