package uz.hiparts.hipartsuz.model.enums;

public enum UserState {
    DEFAULT,
    START,
    LANGUAGE,
    INPUT_LOCATION,
    INPUT_PHONE_NUMBER,
    CATALOG,
    CHOOSE_BRANCH,
    CHOOSE_ORDER_TYPE,
    INPUT_CONFIRM_CODE,
    ADDRESS_DETAILS,
    ADMIN,
    INPUT_PRODUCT_NAME,
    INPUT_PRODUCT_PRICE,
    INPUT_PRODUCT_DESCRIPTION,
    INPUT_PRODUCT_IMAGE,
    INPUT_PRODUCT_DISCOUNT,
    INPUT_CATEGORY_NAME,
    INPUT_CURRENCY,
    CHOOSE_METHOD_SET_ADMIN,
    CHOOSE_METHOD_REMOVE_ADMIN,
    INPUT_ADMIN_USERNAME_FOR_SET,
    INPUT_ADMIN_PHONE_NUMBER_FOR_SET,
    INPUT_ADMIN_USERNAME_FOR_REMOVE,
    INPUT_ADMIN_PHONE_NUMBER_FOR_REMOVE
}
